apiVersion: v1
kind: Pod
metadata:
  name: load-gen
spec:
  containers:
  - image: alexk82/load-gen:latest
    name: load-gen
    env:
      - name: STRESS_TIME_MS
        value: "250"
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1200m"
